//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace _3342_Term_Project.GetShowService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetShowSoap", Namespace="http://tempuri.org/")]
    public partial class GetShow : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRandomShowOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetShow() {
            this.Url = global::_3342_Term_Project.Properties.Settings.Default._3342_Term_Project_GetShowService_GetShow;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRandomShowCompletedEventHandler GetRandomShowCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRandomShow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TVShows[] GetRandomShow() {
            object[] results = this.Invoke("GetRandomShow", new object[0]);
            return ((TVShows[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRandomShowAsync() {
            this.GetRandomShowAsync(null);
        }
        
        /// <remarks/>
        public void GetRandomShowAsync(object userState) {
            if ((this.GetRandomShowOperationCompleted == null)) {
                this.GetRandomShowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRandomShowOperationCompleted);
            }
            this.InvokeAsync("GetRandomShow", new object[0], this.GetRandomShowOperationCompleted, userState);
        }
        
        private void OnGetRandomShowOperationCompleted(object arg) {
            if ((this.GetRandomShowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRandomShowCompleted(this, new GetRandomShowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TVShows {
        
        private string showNameField;
        
        private string showYearsField;
        
        private string showAgeRatingField;
        
        private int showRuntimeField;
        
        private string showGenreField;
        
        private string showDescriptionField;
        
        private string showImageField;
        
        private int showIDField;
        
        /// <remarks/>
        public string ShowName {
            get {
                return this.showNameField;
            }
            set {
                this.showNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShowYears {
            get {
                return this.showYearsField;
            }
            set {
                this.showYearsField = value;
            }
        }
        
        /// <remarks/>
        public string ShowAgeRating {
            get {
                return this.showAgeRatingField;
            }
            set {
                this.showAgeRatingField = value;
            }
        }
        
        /// <remarks/>
        public int ShowRuntime {
            get {
                return this.showRuntimeField;
            }
            set {
                this.showRuntimeField = value;
            }
        }
        
        /// <remarks/>
        public string ShowGenre {
            get {
                return this.showGenreField;
            }
            set {
                this.showGenreField = value;
            }
        }
        
        /// <remarks/>
        public string ShowDescription {
            get {
                return this.showDescriptionField;
            }
            set {
                this.showDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ShowImage {
            get {
                return this.showImageField;
            }
            set {
                this.showImageField = value;
            }
        }
        
        /// <remarks/>
        public int ShowID {
            get {
                return this.showIDField;
            }
            set {
                this.showIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRandomShowCompletedEventHandler(object sender, GetRandomShowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRandomShowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRandomShowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TVShows[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TVShows[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591