//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace _3342_Term_Project.GetMovieService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetMovieSoap", Namespace="http://tempuri.org/")]
    public partial class GetMovie : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRandomMovieOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetMovie() {
            this.Url = global::_3342_Term_Project.Properties.Settings.Default._3342_Term_Project_GetMovieService_GetMovie;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRandomMovieCompletedEventHandler GetRandomMovieCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRandomMovie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Movies[] GetRandomMovie() {
            object[] results = this.Invoke("GetRandomMovie", new object[0]);
            return ((Movies[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRandomMovieAsync() {
            this.GetRandomMovieAsync(null);
        }
        
        /// <remarks/>
        public void GetRandomMovieAsync(object userState) {
            if ((this.GetRandomMovieOperationCompleted == null)) {
                this.GetRandomMovieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRandomMovieOperationCompleted);
            }
            this.InvokeAsync("GetRandomMovie", new object[0], this.GetRandomMovieOperationCompleted, userState);
        }
        
        private void OnGetRandomMovieOperationCompleted(object arg) {
            if ((this.GetRandomMovieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRandomMovieCompleted(this, new GetRandomMovieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Movies {
        
        private string movieNameField;
        
        private int movieYearField;
        
        private string movieDescriptionField;
        
        private int movieRuntimeField;
        
        private string movieAgeRatingField;
        
        private string movieGenreField;
        
        private float movieBudgetField;
        
        private float movieIncomeField;
        
        private int movieIDField;
        
        private string movieImageField;
        
        /// <remarks/>
        public string movieName {
            get {
                return this.movieNameField;
            }
            set {
                this.movieNameField = value;
            }
        }
        
        /// <remarks/>
        public int movieYear {
            get {
                return this.movieYearField;
            }
            set {
                this.movieYearField = value;
            }
        }
        
        /// <remarks/>
        public string movieDescription {
            get {
                return this.movieDescriptionField;
            }
            set {
                this.movieDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int movieRuntime {
            get {
                return this.movieRuntimeField;
            }
            set {
                this.movieRuntimeField = value;
            }
        }
        
        /// <remarks/>
        public string movieAgeRating {
            get {
                return this.movieAgeRatingField;
            }
            set {
                this.movieAgeRatingField = value;
            }
        }
        
        /// <remarks/>
        public string movieGenre {
            get {
                return this.movieGenreField;
            }
            set {
                this.movieGenreField = value;
            }
        }
        
        /// <remarks/>
        public float movieBudget {
            get {
                return this.movieBudgetField;
            }
            set {
                this.movieBudgetField = value;
            }
        }
        
        /// <remarks/>
        public float movieIncome {
            get {
                return this.movieIncomeField;
            }
            set {
                this.movieIncomeField = value;
            }
        }
        
        /// <remarks/>
        public int movieID {
            get {
                return this.movieIDField;
            }
            set {
                this.movieIDField = value;
            }
        }
        
        /// <remarks/>
        public string movieImage {
            get {
                return this.movieImageField;
            }
            set {
                this.movieImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetRandomMovieCompletedEventHandler(object sender, GetRandomMovieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRandomMovieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRandomMovieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movies[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movies[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591